#!/usr/bin/env bash
. settings.sh

if [ $# -lt 1 ]; then
    echo "Usage: $0 <command>

    commands:
        start
        stop
        restart"
    exit
fi

function start() {
    launchctl load "$plist_file"
}

function stop() {
    launchctl unload "$plist_file"
}

function restart() {
    stop
    start
}

case $1 in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
esac
